# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: gitpod/workspace-python-3.10

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

